"""empty message

Revision ID: 0ea8bff98c1c
Revises: b7bdd01307f7
Create Date: 2026-02-02 19:12:04.534091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea8bff98c1c'
down_revision = 'b7bdd01307f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emails_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('emails_enabled')

    # ### end Alembic commands ###
