"""empty message

Revision ID: 7da6ab18baf2
Revises: 60749c12da0e
Create Date: 2026-02-01 21:41:40.175984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da6ab18baf2'
down_revision = '60749c12da0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_type', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('frequency', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('points_reward', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('points_reward')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('frequency')
        batch_op.drop_column('goal_type')

    # ### end Alembic commands ###
