"""empty message

Revision ID: a28bd114b7e2
Revises: 
Create Date: 2026-02-03 04:45:57.964721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28bd114b7e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('url_music', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('goal_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_categories_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('day_start_time', sa.Time(), nullable=False),
    sa.Column('night_start_time', sa.Time(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('emails_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('welcome_email_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.Enum('day', 'night', 'both', name='activitytype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_category', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_external_id'), ['external_id'], unique=True)

    op.create_table('daily_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('day', 'night', name='sessiontype'), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_date', 'session_type', name='uq_session_user_date_type')
    )
    with op.batch_alter_table('daily_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_daily_sessions_user_date', ['user_id', 'session_date'], unique=False)

    op.create_table('goal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Enum('small', 'medium', 'large', name='goalsize'), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['goal_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.create_index('ix_goal_templates_category', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_templates_external_id'), ['external_id'], unique=True)
        batch_op.create_index('ix_goal_templates_frequency', ['frequency'], unique=False)
        batch_op.create_index('ix_goal_templates_size', ['size'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('goal_type', sa.String(length=40), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('size', sa.Enum('small', 'medium', 'large', name='goalsize'), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_value >= 0', name='ck_goal_current_nonneg'),
    sa.CheckConstraint('points_reward >= 0', name='ck_goal_points_nonneg'),
    sa.CheckConstraint('target_value >= 0', name='ck_goal_target_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index('ix_goals_user', ['user_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.Enum('welcome', 'goal_daily', 'activity_daily', 'inactive_nudge', 'day_session', 'night_session', name='remindertype'), nullable=False),
    sa.Column('mode', sa.Enum('fixed', 'inactivity', name='remindermode'), nullable=False),
    sa.Column('local_time', sa.Time(), nullable=True),
    sa.Column('inactive_after_minutes', sa.Integer(), nullable=True),
    sa.Column('days_of_week', sa.String(length=40), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_user', ['user_id'], unique=False)
        batch_op.create_index('ix_reminders_user_type_active', ['user_id', 'reminder_type', 'is_active'], unique=False)

    op.create_table('activity_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_session_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('points_awarded IN (0, 5, 10, 20)', name='ck_activity_points'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['daily_session_id'], ['daily_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_session_id', 'activity_id', name='uq_session_activity')
    )
    with op.batch_alter_table('activity_completions', schema=None) as batch_op:
        batch_op.create_index('ix_activity_completions_activity', ['activity_id'], unique=False)
        batch_op.create_index('ix_activity_completions_session', ['daily_session_id'], unique=False)

    op.create_table('daily_session_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_session_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'done', 'skipped', name='sessiongoalstatus'), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_session_id'], ['daily_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_session_id', 'goal_id', name='uq_session_goal')
    )
    with op.batch_alter_table('daily_session_goals', schema=None) as batch_op:
        batch_op.create_index('ix_session_goals_goal', ['goal_id'], unique=False)
        batch_op.create_index('ix_session_goals_session', ['daily_session_id'], unique=False)

    op.create_table('emotion_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_session_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('intensity >= 1 AND intensity <= 10', name='ck_emotion_checkin_intensity_range'),
    sa.ForeignKeyConstraint(['daily_session_id'], ['daily_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotion_checkins', schema=None) as batch_op:
        batch_op.create_index('ix_emotion_checkins_emotion', ['emotion_id'], unique=False)
        batch_op.create_index('ix_emotion_checkins_session', ['daily_session_id'], unique=False)

    op.create_table('goal_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('daily_session_id', sa.Integer(), nullable=True),
    sa.Column('delta_value', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_session_id'], ['daily_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_progress', schema=None) as batch_op:
        batch_op.create_index('ix_goal_progress_goal', ['goal_id'], unique=False)
        batch_op.create_index('ix_goal_progress_session', ['daily_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_progress_session')
        batch_op.drop_index('ix_goal_progress_goal')

    op.drop_table('goal_progress')
    with op.batch_alter_table('emotion_checkins', schema=None) as batch_op:
        batch_op.drop_index('ix_emotion_checkins_session')
        batch_op.drop_index('ix_emotion_checkins_emotion')

    op.drop_table('emotion_checkins')
    with op.batch_alter_table('daily_session_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_session_goals_session')
        batch_op.drop_index('ix_session_goals_goal')

    op.drop_table('daily_session_goals')
    with op.batch_alter_table('activity_completions', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_completions_session')
        batch_op.drop_index('ix_activity_completions_activity')

    op.drop_table('activity_completions')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_user_type_active')
        batch_op.drop_index('ix_reminders_user')

    op.drop_table('reminders')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index('ix_goals_user')

    op.drop_table('goals')
    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_templates_size')
        batch_op.drop_index('ix_goal_templates_frequency')
        batch_op.drop_index(batch_op.f('ix_goal_templates_external_id'))
        batch_op.drop_index('ix_goal_templates_category')

    op.drop_table('goal_templates')
    with op.batch_alter_table('daily_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_sessions_user_date')

    op.drop_table('daily_sessions')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_external_id'))
        batch_op.drop_index('ix_activities_category')

    op.drop_table('activities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('goal_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_categories_name'))

    op.drop_table('goal_categories')
    op.drop_table('emotions')
    op.drop_table('activity_categories')
    # ### end Alembic commands ###
