"""create goal templates and categories

Revision ID: b7bdd01307f7
Revises: 7da6ab18baf2
Create Date: 2026-02-02 00:39:36.074208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b7bdd01307f7'
down_revision = '7da6ab18baf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_categories_name'), ['name'], unique=True)

    goal_size_enum = postgresql.ENUM(
    'small', 'medium', 'large',
    name='goalsize',
    create_type=False
    )   
    op.create_table('goal_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('size', goal_size_enum, nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['goal_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.create_index('ix_goal_templates_category', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_templates_external_id'), ['external_id'], unique=True)
        batch_op.create_index('ix_goal_templates_frequency', ['frequency'], unique=False)
        batch_op.create_index('ix_goal_templates_size', ['size'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_templates_size')
        batch_op.drop_index('ix_goal_templates_frequency')
        batch_op.drop_index(batch_op.f('ix_goal_templates_external_id'))
        batch_op.drop_index('ix_goal_templates_category')

    op.drop_table('goal_templates')
    with op.batch_alter_table('goal_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_categories_name'))

    op.drop_table('goal_categories')
    # ### end Alembic commands ###
